import streamlit as st
from utils import (
    create_email_chain,
    create_study_plan_chain,
    create_knowledge_qna_chain,
    create_action_items_chain,
    initialize_agent_executor,
    get_llm_instance
)

llm = get_llm_instance()

# Create all chains and the agent executor once to avoid repeated initialization
email_chain = create_email_chain(llm)
study_plan_chain = create_study_plan_chain(llm)
knowledge_qna_chain = create_knowledge_qna_chain(llm)
action_items_chain = create_action_items_chain(llm)
agent_executor = initialize_agent_executor()


st.title("Personal Assistant with LangChain")

task_type = st.sidebar.selectbox("Select a Task", [
    "Draft Email", "Knowledge-Based Q&A",
    "Generate Study Plan", "Extract Action Items", "Tool-Using Agent"
])

if task_type == "起草邮件":
    st.header("基于Context起草一封邮件")
    context_input = st.text_area("请输出邮件内容:")
    if st.button("起草邮件"):
        result = email_chain.run(context=context_input)
        st.text_area("Generated Email", result, height=300)

elif task_type == "Q&A":
    st.header("知识问答")
    domain_input = st.text_input("请输入知识领域 (e.g.,财经类,技术类,健康类):")
    question_input = st.text_area("输入你的问题:")
    if st.button("Get Answer"):
        result = knowledge_qna_chain.run(question=question_input, domain=domain_input)
        st.text_area("Answer", result, height=300)

elif task_type == "Generate Study Plan":
    st.header("Generate a Personalized Study Plan")
    topic_input = st.text_input("Enter the topic to study:")
    duration_input = st.text_input("Enter the duration (e.g., 2 weeks, 1 month):")
    if st.button("Generate Study Plan"):
        result = study_plan_chain.run(topic=topic_input, duration=duration_input)
        st.text_area("Study Plan", result, height=300)

elif task_type == "Extract Action Items":
    st.header("Extract Action Items from Meeting Notes")
    notes_input = st.text_area("Enter meeting notes:")
    if st.button("Extract Action Items"):
        result = action_items_chain.run(notes=notes_input)
        st.text_area("Action Items", result, height=300)

elif task_type == "Tool-Using Agent":
    st.header("Tool-Using Agent")
    agent_input = st.text_input("Enter your query (e.g., 'Draft an email thanking the team for their hard work'): ")
   
    if st.button("Run Agent"):
        try:
            execution_results = agent_executor(agent_input)
           
            if isinstance(execution_results, dict) and 'intermediate_steps' in execution_results and execution_results['intermediate_steps']:
                final_result = execution_results['intermediate_steps'][-1][1]  
            else:
                final_result = execution_results.get('output', 'No meaningful output was generated by the agent.')

            st.text_area("Agent Output", final_result, height=300)
       
        except Exception as e:
            st.error(f"An error occurred while running the agent: {str(e)}")